### ISSUE TITLE
ignore tags that don't match the prefix

### ISSUE THREAD

**Issue by isnok** [python-versioneer/python-versioneer#110]
Currently versioneer expects (all?) tags in the repository to match the given (`tag_prefix`).
If (the latest?) tag does not match that prefix, versioneer will not be able to derive a version.

I have a repo, in which i maintain mulltiple packages. This is waiting for a fix to https://github.com/warner/python-versioneer/issues/38 (dup: https://github.com/warner/python-versioneer/issues/109) anyway, but i noticed, that that won't be enough. I want to use separate tag prefixes for the different packages, but it seems like if i add a tag with a new prefix, the "previous" package does not get a version anymore, because it fails on the wrong prefix of the more recent tag.

Proposed fix: If a tag does not match `tag_prefix`, just ignore the tag.

**Comment by warner** [comment]
Hm.. so you've got multiple tags (like `foo-1.2` and `bar-4.7`) in a single repository, with some subdirectories or packages that want to pay attention to `foo-*` and others that want to pay attention to `bar-*`?

As far as I know, `git describe` only tells us about the most recent tag: there's no way to say "please find the most recent tag that matches the pattern `foo-*` and give me a description based upon that". Let's see.. to do that, I think we'd have to stop using `git describe` and instead write code that walks the list of tags, filters for the prefix, filters again for ones that are ancestors of HEAD, then for each one it would build a list of revisions between that tag and HEAD (`git rev-parse $TAG..HEAD`), count the number of revisions, then return the one with the shortest list, then build the equivalent of `git describe`'s output based upon that tag.

It wouldn't work at all for `git archive` tarballs, but I think normal in-between-tags versions don't work there either.

**Comment by isnok** [comment]
You're right. I also found, that you can use `git rev-list --count <range>` to have git count the number of revisions in `<range>`. Hope that helps.

**Comment by effigies** [comment]
This has been supported for a while.
