### ISSUE TITLE
merge with setuptools_scm ?

### ISSUE THREAD

**Issue by warner** [python-versioneer/python-versioneer#111]
I only recently learned about https://github.com/pypa/setuptools_scm/ , which is "the blessed package to manage your versions by scm tags". I haven't looked at it closely to see how its features compare against Versioneer, but maybe there's some way to combine these.

One disadvantage I see right off the bat is that `setuptools_scm` needs a `setup_requires=` clause (since it's a plugin for setuptools), and I've been taught to avoid those (one reason is that it's harder to do peep-style check-hashes-of-dependencies stuff). It might be possible to put a `setuptools_scm-XYZ.egg` in the project root directory, to avoid a download.

This might also address Glyph's thoughts in #42.

**Comment by piotr-dobrogost** [comment]
Speaking of similar projects, there's this new extension for mercurial – https://pypi.python.org/pypi/mercurial_update_version/

**Comment by michaelaye** [comment]
But I think `setuptools_scm` does not deal with `<module_name>.__version__` but focuses on setup.py version identification. And that's something that `versioneer` exactly does not do, at least I don't see any mentioning of setup.py and what to do there about the version string? So maybe there isn't that much overlap after all?

**Comment by RonnyPfannschmidt** [comment]
hi, im the author of setuptools_scm

there are multiple ways supported of putting the version into modules, based on package metadata or telling it to write it to an actual module/file

setuptools_scm is all about that

as for putting eggs into python-path, that will be a pain, it may be more versatile to put a wheel into the pythonpath, an dit may be a good idea to document that

**Comment by effigies** [comment]
Tagging this with documentation as we should link out to related projects.
