### ISSUE TITLE
leftover __pycache__ breaks tests

### ISSUE THREAD

**Issue by warner** [python-versioneer/python-versioneer#112]
Whenever I run the tests locally (with something like `tox -e py27`) multiple times, I always get an error during the `python setup.py make_versioneer` step like this:

```
py27 runtests: commands[2] | python setup.py make_versioneer
running make_versioneer
error: src/__pycache__/long_header.py: No such file or directory
ERROR: InvocationError: '/Users/warner/stuff/python/python-versioneer/.tox/py27/bin/python setup.py make_versioneer'
```

I fix this by finding and deleting all the `__pycache__` directories. But I'd like it to be automatic.

**Comment by jsacrist** [comment]
Hi, I was playing with versioneer for a few days and ran into this problem as well.
I think ended up fixing a few problems that would make the build jobs (tox and travis-ci) fail.
How active is the development of this project as of today?

Thanks
