### ISSUE TITLE
give up on python-2.6?

### ISSUE THREAD

**Issue by warner** [python-versioneer/python-versioneer#113]
I think we can retain support for a while, but if we ever do drop it, here's a list of things that could be cleaned up:
- remove the hacks/stand-ins for `unittest.skip` and `unittest.expectedFailure` in test_invocations.py
- maybe use --isolated everywhere (test_invocations.py)
- use `with TarFile(Sdist) as t` in `test_sdist` (test_invocations.py)
- switch to `assertNotIn`/`assertIn` (test_invocations.py)

**Comment by effigies** [comment]
Need to check whether I got all of this in #216. Forgot to check before merging.
