### ISSUE TITLE
Versioneer does not write import inside __init__.py in accordance with versionfile_source

### ISSUE THREAD

**Issue by AndreiPashkin** [python-versioneer/python-versioneer#123]
Example:

``` ini
[versioneer]
...
versionfile_source = src/myproject/__version__.py
versionfile_build = myproject/__version__.py
...
```

With that config `versioneer install` writes file `__version__.py`, but in `__init__.py` writes:

``` python
from ._version import get_versions
__version__ = get_versions()['version']
del get_versions
```

Notice - `from ._version ...`, not `from .__version__ ...`.

**Comment by warner** [comment]
Oops, good catch. Looks like we should be using `INIT_PY_SNIPPET` (in src/setupfunc.py) as a template, and populate the import statement using the relative filename that we extract from `versionfile_build`. I'll see if I can assemble a test and a patch.

**Comment by cfobel** [comment]
This is still an issue, as seen in [`src/setupfunc.py`][1].

[1]: https://github.com/warner/python-versioneer/blob/92f3dc4b738d223bf9cc549aac35018f2e02bd04/src/setupfunc.py#L47-L51
