### ISSUE TITLE
doesn't work on Windows?

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [python-versioneer/python-versioneer#14]
A pycryptopp user reported this bug:

https://tahoe-lafs.org/trac/pycryptopp/ticket/95

Is it possible that versioneer's attempt to invoke "git" as a command in order to learn the version number has just never been tested on Windows?

**Comment by warner** [comment]
@chiiph @bryevdv I believe this should be fixed in the current version (0.15).. could you test it out? Thanks!

**Comment by bryevdv** [comment]
@warner we are in the middle of a release so it will take some time to get to. I believe we have also made some customizations to support our build automation, so we may have to stay where we are because of that. ping @damianavila

**Comment by bryevdv** [comment]
Stumbled across this. FWIW we are now using versioneer 0.17 and things work fine across all the platforms we run.

**Comment by effigies** [comment]
@bryevdv Thanks for the report back. I'll close this for now, and we can open a new issue if it returns.
