### ISSUE TITLE
git tag 0.18 mismatch code version on PyPI

### ISSUE THREAD

**Issue by marscher** [python-versioneer/python-versioneer#143]
I just wanted to try out the introduced patching of an existing cmd class. The signature of get_cmdclass now takes an optional argument to pass in a command class, but the release on PyPI does not have this code.

I upgraded from version 0.16:
```
$ versioneer install 
replacing old versioneer.py (0.16)
versioneer.py (0.18) installed into local tree
Now running 'versioneer.py setup' to install the generated files..
 creating pyemma/_version.py
 appending to pyemma/__init__.py
 'versioneer.py' already in MANIFEST.in
 versionfile_source already in MANIFEST.in
```

So I doubt that the base64 encode of the implementation is really at the state of tag 0.18. I've verified this locally by downloading the wheel and writing a fresh install. The signature is not matching.

**Comment by effigies** [comment]
Yes, versions in versioneer are handled manually. I've updated the source to be `0.19.dev0` until the next release.
