### ISSUE TITLE
Support pyproject.toml instead of setup.cfg

### ISSUE THREAD

**Issue by dstufft** [python-versioneer/python-versioneer#146]
PEP 518 added ``pyproject.toml``, a file that tools like versioneer can use instead of a random assortment of tools. Thus it would be great if versioneer could support it. The only thing it really has to take care is to namespace all of its keys below ``tool.versioneer``, so like:

```TOML
[tool.versioneer]
style = "pep440"
```

**Comment by igonro** [comment]
Any progress with this?

**Comment by jlumbroso** [comment]
This would involve editing this portion of the package + adding tests:
https://github.com/python-versioneer/python-versioneer/blob/4f6072bd65e443a91c5f8c30f736cf01e47b6409/src/header.py#L22-L87

**Comment by effigies** [comment]
I would be happy to review a PR...

**Comment by ashutoshvarma** [comment]
Any one working on this? It would be great if pyproject.toml is supported.

**Comment by effigies** [comment]
Not that I've seen.

**Comment by BrianThomasRoss** [comment]
Where could I find contribution guidelines?

**Comment by effigies** [comment]
> Where could I find contribution guidelines?

@BrianThomasRoss Apologies for the slow response. There are currently no contribution guidelines. It's pretty old-school, for better or worse. If someone wanted to contribute contribution guidelines, I'd be happy to edit with things I've picked up from working on this off-and-on for a year or so.

Separately, I'll probably work on this issue next if nobody else jumps in to contribute it first.
