### ISSUE TITLE
versioneer.get_cmdclass doesn't take any argument

### ISSUE THREAD

**Issue by kevintandean** [python-versioneer/python-versioneer#161]
In installation.md it is said that we can override cmdclass this way:
`cmdclass=versioneer.get_cmdclass(numpy_cmdclass)`.

On 0.18 get_cmdclass defined on the generated versioneer.py is for some reason defined without optional argument.
```
def get_cmdclass():
    """Get the custom setuptools/distutils subclasses used by Versioneer."""
    if "versioneer" in sys.modules:
        del sys.modules["versioneer"]
        # this fixes the "python setup.py develop" case (also 'install' and
        # 'easy_install .'), in which subdependencies of the main project are
        # built (using setup.py bdist_egg) in the same python process. Assume
        # a main project A and a dependency B, which use different versions
        # of Versioneer. A's setup.py imports A's Versioneer, leaving it in
        # sys.modules by the time B's setup.py is executed, causing B to run
        # with the wrong versioneer. Setuptools wraps the sub-dep builds in a
        # sandbox that restores sys.modules to it's pre-build state, so the
        # parent is protected against the child's "import versioneer". By
        # removing ourselves from sys.modules here, before the child build
        # happens, we protect the child from the parent's versioneer too.
        # Also see https://github.com/warner/python-versioneer/issues/52

    cmds = {}
```

**Comment by mcflugen** [comment]
@kevintandean I had this same problem.

It looks like the latest release of versioneer (0.18) was on 1 Jan but the change to `get_cmdclass` that adds the `cmdclass` keyword wasn't added until 2 Jan. Anyway, installing versioneer from source fixed this problem.

**Comment by jacobtomlinson** [comment]
Installing from source worked for me too. Would be great to get a new release with this in.

**Comment by reedstrm** [comment]
Still need a release that fixes this!

**Comment by navjotk** [comment]
Still need this!

**Comment by hhslepicka** [comment]
Still need this...

**Comment by effigies** [comment]
Tagging this with 0.19 so we can close on release.

**Comment by effigies** [comment]
0.19 is released.

**Comment by jeeva-srinivasan** [comment]
still facing this issue - " AttributeError: module 'versioneer' has no attribute 'get_cmdclass'  "
even after using the 0.19 version
