### ISSUE TITLE
The main module (in /usr/lib/pythonX.Y/site-packages) should be installed under a different name.

### ISSUE THREAD

**Issue by anntzer** [python-versioneer/python-versioneer#165]
Currently, assuming that one has a package where the main python package is in the toplevel directory
```
.git
mypkg/__init__.py
mypkg/_version.py
versioneer.py
```
(which is a fairly common setup, although I know there's the eternal debate of whether `mypkg` should go under a `src` subdirectory), then pip-editable-installing this package (pip install -e .) would also cause a versioneer.py (the "generated" module) to be present into sys.path, different from, and shadowing, the one that actually powers the versioneer CLI (the "main" module).  For example, invoking /usr/bin/versioneer would fail after such an install.

I think the easiest way to fix the issue is to either rename the "main" module to `_versioneer` (or `versioneer_cli` if you want to keep it public, although it's not clear why you'd bother -- if you want to invoke versioneer programatically(!) you can always go through a subprocess), or not install a module at all and simply install a single file as a `script` (https://packaging.python.org/tutorials/distributing-packages/#scripts).

Edit: Another advantage of having the main module under a different name is that this allows one to differentiate between importing the main module and the generated module, e.g. in a copy-pasted function in setup.py that tries to determine whether the generated module is present.

**Comment by effigies** [comment]
With isolated builds being common, and versioneer having non-vendored installation, I'm going to say this isn't going to happen.
