### ISSUE TITLE
get_version() includes prefix 'refs/tags/' 

### ISSUE THREAD

**Issue by tovop** [python-versioneer/python-versioneer#166]
My build fails because the version string returned by get_version() (git describe)  contains '/refs/tags'.

Am I doing something wrong when tagging or is it some kind of bug? Is there a way to remove the prefix by e.g. Split('/') [-1]?

**Comment by jcfr** [comment]
In order to reproduce and debug the issue, could you share a reference to your project (or sample project allowing to do so) ?

**Comment by effigies** [comment]
If this was not answered by @ccharlesgb, please reopen.
