### ISSUE TITLE
Wheel packages with extensions do not get static version file

### ISSUE THREAD

**Issue by pkittenis** [python-versioneer/python-versioneer#170]
For packages containing native code extensions, versioneer will not bundle a static version file when creating a wheel. `sdist` distributions do get static file.

For example:

```
wget https://files.pythonhosted.org/packages/c6/76/cb7ac54f89dfb0a43dab5f15e7a7cfffc7755379af53bd833b731cca79df/ssh2_python-0.9.0-cp27-cp27m-manylinux1_x86_64.whl
```

`ssh2/_version.py`  in the wheel is the git version and requires git to be installed.

The [source distribution package](https://files.pythonhosted.org/packages/b4/fe/59da3f4428ffc614505f7df119225fe9f0dd2e998007a7d7fe843f861525/ssh2-python-0.9.0.tar.gz) on the other hand has the static version.

**Comment by djhoese** [comment]
I'm running in to this same issue when building my package on travis CI. I think this is the same issue described in #129. Using travis' builtin deploy stuff it seems they run `sdist` and `bdist_wheel` as separate commands or at least it doesn't work as we hope/expect.

Does anyone have some work arounds for this?
