### ISSUE TITLE
Versioneer is not PEP8 compliant

### ISSUE THREAD

**Issue by giampaolo** [python-versioneer/python-versioneer#175]
In our code base `flake8` is part of our development process. It is run on commit via GIT hook and our CI testing also runs committed code through it. 
Since `versioneer.py` is added to our repo that is also run through `flake8`. That forces us to PEP8-ify it. It would be great if this is done upstream, in here. 
Thoughts?

**Comment by Juanlu001** [comment]
Would the maintainers accept a pull request making versioneer PEP8 compliant?

**Comment by alimcmaster1** [comment]
> Would the maintainers accept a pull request making versioneer PEP8 compliant?

I’m not a maintainer - but this should be simple to fix I can open a PR.

**Comment by effigies** [comment]
Should have been fixed in #213. Please reopen if you're still having issues.

Note that there hasn't been a release, so you'll need to install from source for the time being.
