### ISSUE TITLE
Minified minimal versioneer

### ISSUE THREAD

**Issue by basnijholt** [python-versioneer/python-versioneer#176]
I've been a bit reluctant to add `versioneer` to my small projects simply because `versioneer` sometimes has more lines of code than the project I am adding it too.

My colleague just made a "minimal versioneer" [`minver`](https://github.com/jbweston/miniver) which has the same functionality but in about 180 lines (vs 2500 lines). Probably it's less general than `versioneer` and not as well tested.

This issue just serves as a reference for people in the future that might search for this (I certainly did).

**Comment by effigies** [comment]
Let's add related projects to the docs.
