### ISSUE TITLE
Create Changelog from tag messages

### ISSUE THREAD

**Issue by jakirkham** [python-versioneer/python-versioneer#178]
One of the things I really admire about Git is how easy it is to just add changelog information into an annotated tag, `git tag -a`. Combined with how GitHub picks up on this information and makes it pretty trivial to publish as part of the GitHub release is even better.

However I forget in this process that users sometimes like a Changelog file and like seeing this in things like `sdist`s. It would be nice if there was an option in versioneer to autogenerate this Changelog file from the Git tag annotations. That way users can get at this information as easily as I can generate it.

**Comment by effigies** [comment]
Cool idea, and I think you could use similar code but I doubt with the level of energy there is in this project that this will ever happen.
