### ISSUE TITLE
Does it have any plan to support pyinstaller 

### ISSUE THREAD

**Issue by x007007007** [python-versioneer/python-versioneer#184]
I user versioneer with pyinstaller，version will unknown。 Could we support pyinstaller

**Comment by georgek** [comment]
I use versioneer with pyinstaller and it works fine. Could you describe your problem more?

**Comment by zegervdv** [comment]
for me it seems it doesn't do the freeze. So the app tries to run git to figure out the version in stead of having the version hard-coded.
When you build a wheel, the _version.py file is overwritten with hard-coded values.
Maybe we are missing a setting somewhere?

**Comment by georgek** [comment]
I'm doing mine as a two-step process. First I build the project with `python setup.py build`, which freezes the version number etc., then I run pyinstaller against the build. This makes sense to me. I wouldn't expect pyinstaller to work from the unbuilt source code.

**Comment by zegervdv** [comment]
I see, I thought it worked like `cx_freeze` and did the build step by itself.
How do you point it to use the build version?

**Comment by georgek** [comment]
This might not be the only way to do it, but this is how I do it and it works:

In my packages I don't usually include any executables/scripts, but I instead use the `entry_points` option in my `setup.py` which will automatically create scripts stubs when you *install* the package (not build) with pip (see https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation ) So after building I get something like `build/lib/my_package`.

For pyinstaller I then write my own little stub in its own directory like `pyinstaller/my_package.py` that simply imports my package and calls one of the entry points:
```
import my_package
if __name__ == "__main__":
    my_package.main.main()
```

The call pyinstaller with the `--paths` option, e.g. `pyinstaller --paths build/lib pyinstaller/my_package.py`. This way it will find your built version of your package.

If it would help I could put together a little barebones example package.

**Comment by zegervdv** [comment]
Got it to work. Thanks for taking the time to explain!
