### ISSUE TITLE
untagged version despite present tags

### ISSUE THREAD

**Issue by mluerig** [python-versioneer/python-versioneer#191]
I just installed versioneer into an existing project (https://github.com/mluerig/phenopype), but I keep getting "untagged" when I load my package and run

    versioneer.get_versions()

    {'version': '0+untagged.109.g4c75dd5.dirty',
     'full-revisionid': '4c75dd5a0da4b833aaab4319b0580b0c74174c5d',
     'dirty': True,
     'error': None,
     'date': '2018-12-09T14:41:34+0100'}

yet when I do 

    (pp37) E:\Python1\phenopype>git show 0.4.8

    commit 4c75dd5a0da4b833aaab4319b0580b0c74174c5d (HEAD -> master, tag: 0.4.8, tag: 0.4.7, 
    origin/master, origin/HEAD)
    Author: Moritz L<C3><BC>rig <moritz.luerig@gmail.com>
    Date:   Sun Dec 9 14:41:34 2018 +0100

        example update

it gives me the tag - what am I doing wrong?

maybe related to https://github.com/warner/python-versioneer/issues/179, but I don't get what he meant by "re-run versioneer setup"

**Comment by moggers87** [comment]
I assume they mean run `versioneer install` again.

I came across this bug report while trying to solve a similar issue. It looks like versioneer keeps a copy of its settings in both `setup.cfg` and the `_version.py` it creates.

**Comment by charlesbaynham** [comment]
I had this problem, but realised it was my fault: versioneer filters by the `tag_prefix` in `setup.cfg`, so will only detect tags that start with this string if you've included it.

**Comment by effigies** [comment]
Please reopen if this is still an issue.
