### ISSUE TITLE
How to use??

### ISSUE THREAD

**Issue by jamiejackherer** [python-versioneer/python-versioneer#198]
After spending 20 mins looking for the most simple "How to" on using Versioneer, I could findhow to use this tool. Is there ANY docs? Is there even a simple "run XYZ command"?? It would seem you do not let people know how to use this tool... Am I wrong?

**Comment by lewisacidic** [comment]
Out of interest, where were you looking?

Literally first subsection of the readme:
https://github.com/warner/python-versioneer#quick-install

For more detailed instructions:
https://github.com/warner/python-versioneer#installation

**Comment by irgeek** [comment]
Literally from the first section of the readme:
> add a [versioneer] section to your setup.cfg (see below)
... but there is nothing below about that section to see

There is a link to the [INSTALL.md](https://github.com/warner/python-versioneer/blob/master/INSTALL.md) file below which says:
> See "Styles" below for details.
... but again there is no section below about the styles

As someone coming to this tool without knowing how to use it, the above is a _really_ frustrating experience and puts me off wanting to use it.
