### ISSUE TITLE
SafeConfigParser renamed to ConfigParser

### ISSUE THREAD

**Issue by mattconway1984** [python-versioneer/python-versioneer#200]
According to the doc page [here](https://docs.python.org/2/library/configparser.html):

> Note The ConfigParser module has been renamed to configparser in Python 3. The 2to3 tool will automatically adapt imports when converting your sources to Python 3.

I checked this after installing versioneer into one of my projects:

```
Now running 'versioneer.py setup' to install the generated files..
versioneer.py:342: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  parser = configparser.SafeConfigParser()
versioneer.py:344: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  parser.readfp(f)
```

**Comment by ericfrederich** [comment]
FYI, this still seems to work in Python 3.8.  Still safe for now.  Really should fix this though.  For a project which aims to be compatible with Python 2.7 perhaps it needs some `compat.py` or utilize `six`

**Comment by alimcmaster1** [comment]
Merge request #207 should fix this

**Comment by effigies** [comment]
Fixed in master.
