### ISSUE TITLE
flake8 complaint

### ISSUE THREAD

**Issue by vstavrinov** [python-versioneer/python-versioneer#201]
flake8 versioneer.py 
versioneer.py:564:35: W605 invalid escape sequence '\s'
versioneer.py:568:35: W605 invalid escape sequence '\s'
versioneer.py:572:35: W605 invalid escape sequence '\s'
versioneer.py:613:52: W605 invalid escape sequence '\d'
versioneer.py:689:33: W605 invalid escape sequence '\d'

I use flake8 with automated testing and continuous  integration and don't want remove this useful tool. So it is a problem. Could you fix this?

**Comment by effigies** [comment]
Closed by #213.
