### ISSUE TITLE
cannot import name 'main' from 'versioneer' (/usr/local/bin/versioneer.py)

### ISSUE THREAD

**Issue by MarkWieczorek** [python-versioneer/python-versioneer#202]
`versioneer install` on macOS (python3.7) crashes with the error

```
Traceback (most recent call last):
  File "/usr/local/bin/versioneer", line 6, in <module>
    from versioneer import main
ImportError: cannot import name 'main' from 'versioneer' (/usr/local/bin/versioneer.py)
```

In short, there is no "main" submodule in versionereer.

**Comment by effigies** [comment]
Do you have any details about your setup? How did you install versioneer?

**Comment by MarkWieczorek** [comment]
I'm going to close this issue, because ~1 year later when I retried using versioneer, it worked. It is possible that this was a bug that was fixed.
