### ISSUE TITLE
Python 3.9 no distribution option cdmclass

### ISSUE THREAD

**Issue by hajnalmt** [python-versioneer/python-versioneer#209]
```
usr/lib64/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cmdlass'
  warnings.warn(msg)
```
also after running setup.py throws a warn, that the produced version number is not PEP440 compilant.
`
/usr/lib/python3.9/site-packages/setuptools/dist.py:468: UserWarning: The version specified is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.`

I used versioneer 0.18 and setuptools 47.3.1.

Is this project maintained at all?

**Comment by effigies** [comment]
This might be a typo. `cmdclass` not `cmdlass`?

**Comment by hajnalmt** [comment]
Jeez thank you, I closed the issue...
