### ISSUE TITLE
prevent/warn register+upload with "-dirty" version

### ISSUE THREAD

**Issue by warner** [python-versioneer/python-versioneer#21]
@dsoprea noticed (in #20) that it's much too easy to upload a `-dirty` version to PyPI. Some alternatives that would be safer:
- show a warning, and give the user a chance to bail
- refuse to upload or register `-dirty` versions without an override flag

**Comment by warner** [comment]
FWIW, the new "style" branch will express this as a boolean. So you could put something in your `setup.py` like:

```python
if versioneer.get_version()["dirty"]:
    raise DontUploadDirtyTarballsError("please commit first")
```

**Comment by warner** [comment]
I think the next step for this ticket might be to add a config option like `no_register_dirty=True`, which (if present) will hook the `setup.py register` function to check for `get_versions()["dirty"]` and throw an exception. Also for the `upload` command.

**Comment by isnok** [comment]
PyPI rejects non-PEP440 versions anyway. So anything that doesn't match
```
[N!]N(.N)*[{a|b|rc}N][.postN][.devN]
```
won't land there anyway.

**Comment by effigies** [comment]
> PyPI rejects non-PEP440 versions anyway. So anything that doesn't match
> 
> ```
> [N!]N(.N)*[{a|b|rc}N][.postN][.devN]
> ```
> 
> won't land there anyway.

And `register` and `upload` were deprecated (https://github.com/pypa/setuptools/pull/1410) and removed (https://github.com/pypa/setuptools/pull/1898) by setuptools.

Further work on this issue would be a waste of time IMO. Closing. Please reopen if you disagree.
