### ISSUE TITLE
Why does versioneer only work in development?

### ISSUE THREAD

**Issue by soerendip** [python-versioneer/python-versioneer#212]
I am using versioneer and I am quite happy with it. Though, when I deploy the code versioneer assigns version 0 for some strange reason. Is there anything in the config that I have to adjust to make it work with deployed code. E.g. when I put my code to pypi load the module I get version 0+unknown.

My code is available via pip:

    pip install ms-mint

or here: https://github.com/soerendip/ms-mint

**Comment by bucknerns** [comment]
Looks like you didn't vendor versioneer properly. You aren't using the command class in your setup.py the _version doesn't have all of versioneers code.
Try this
https://github.com/soerendip/ms-mint/pull/3/files

**Comment by effigies** [comment]
Looks like this is resolved. Please reopen if I'm mistaken.

**Comment by soerendip** [comment]
Hi, 

yes, it works now. Thank you so much for your effort!!!

Cheers
