### ISSUE TITLE
Proper format of _version.py

### ISSUE THREAD

**Issue by NEGU93** [python-versioneer/python-versioneer#214]
What would be the proper format needed for `_version.py`?

I created a one-line file `_version.py` that just contained the line: `__version__ = 0.0.21` based on [this](https://www.thetopsites.net/article/58549477.shtml) and [this answer](https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package/7071358#7071358). However, the function [versions_from_file](https://github.com/python-versioneer/python-versioneer/blob/64a606dea4db7ba776d64678d65564c3d9572d20/src/from_file.py#L24) that is the one that ends up reading this file is actually looking at a `version_json = ` format.

The readme says: 

> a `_version.py` created by some earlier build step

Which one? How?

**Comment by effigies** [comment]
Can you clarify what your goal is? If you want to manually set `__version__`, then versioneer won't do anything useful for you.

**Comment by NEGU93** [comment]
You are right. I'm using it because cookie-cutter came with it by default (and I had no knowledge whatsoever on how to manage versions honestly).
