### ISSUE TITLE
Versioneer deleting function named `get_versions()` from module

### ISSUE THREAD

**Issue by Matt-Hicks-Bose** [python-versioneer/python-versioneer#218]
As seen in Versioneer 0.18

The Versionner install script adds the following lines to the end of the specified `__init__.py` file:
```python
from ._version import get_versions
__version__ = get_versions()['version']
del get_versions
```

However, this has the side-effect of deleting any object in the root of the module with the name `get_versions`. This caused my code to stop working when I installed Versionner, as this was already a name used by the module.

I think that something like this would be better, in that it does not affect any objects that are not already going to be modified by the code:
```python
from ._version import get_versions as __version__
__version__ = __version__()['version']
```

This eliminates the risk of namespace collisions (except for `__version__` of course), but I am not sure if this will work correctly in all use cases of Versioneer. It seems to be working correctly for a repository installed in editable mode on my system.

**Comment by effigies** [comment]
Seems like a reasonable change. Care to make a PR?

**Comment by effigies** [comment]
Actually, why not:

```Python
from . import _version
__version__ = _version.get_versions()['version']
```

`pkg._version` is a valid import, is marked "private", so no need to delete anything.
