### ISSUE TITLE
ImportError: cannot import name 'main'

### ISSUE THREAD

**Issue by biakota** [python-versioneer/python-versioneer#226]
![Screenshot 2020-10-22 105342](https://user-images.githubusercontent.com/31109910/96822702-e19e7a00-1454-11eb-8f7b-e5742c285258.png)

i am beginner on versioneer; someone can tell me why this error?

**Comment by effigies** [comment]
Could you provide more context for how you got to this point? How did you install versioneer, and how did you call it?
