### ISSUE TITLE
'versioneer install' doesn't respect versionfile_source's filename when modifying __init__.py

### ISSUE THREAD

**Issue by staticintlucas** [python-versioneer/python-versioneer#240]
I want to use a different filename for my _version.py, so in my setup.cfg I set:

    versionfile_source = src/someotherfile.py

When I run `versioneer install` this correctly generates that file and adds it to my MANIFEST.in.

However in my __init__.py it adds:

    from ._version import get_versions

instead of:

    from .someotherfile import get_versions

If I manually modify this line everything else seems to work as expected.

**Comment by effigies** [comment]
Thanks for the report. Yes, this is a known issue (#123), and it appears that #138 was a first pass at resolving it.

Would you be interested in taking a shot at fixing it?

**Comment by staticintlucas** [comment]
Oops, I hadn't seen the original bug report. Feel free to close this as duplicate.

I can have a look at fixing it in the next week or two.
