### ISSUE TITLE
Suggestions for linters

### ISSUE THREAD

**Issue by bryevdv** [python-versioneer/python-versioneer#246]
We aways have to make the following two hand-edits to versioneer's updates to keep our linter/code quality tools happy:

* `_version.py` and `versioneer.py` start with blank lines, which trips up our linter. Initial blank lines deleted
* unused loop variable `i` in a `for i in range(3)` flagged, converted to `for _ in range(3)`
* also unused loop var in `for i in cfg.versionfile_source.split('/'):` 

Would it be possible to make these changes here upstream? (Happy to submit a PR myself if it would be accepted)

**Comment by tanvimoharir** [comment]
Hi,
I have found few more lint warnings after my ci pipeline had failed with these:
/_version.py:116:8: R1705: Unnecessary "else" after "return" (no-else-return)
/_version.py:114:8: W0612: Unused variable 'i' (unused-variable)
/_version.py:182:11: R1718: Consider using a set comprehension (consider-using-set-comprehension)
/_version.py:186:11: R1718: Consider using a set comprehension (consider-using-set-comprehension)
/_version.py:195:15: R1718: Consider using a set comprehension (consider-using-set-comprehension)
/_version.py:219:51: W0621: Redefining name 'run_command' from outer scope (line 70) (redefined-outer-name)
/_version.py:230:4: W0612: Unused variable 'out' (unused-variable)
/_version.py:503:12: W0612: Unused variable 'i' (unused-variable)

I am interested in fixing this ,let me know if I can help out.
Thanks!

**Comment by effigies** [comment]
Hi, thanks for this. I'd be fine with reviewing fixes for linters, as long as they don't make things less clear.

xref https://github.com/python-versioneer/python-versioneer/issues/167

**Comment by bryevdv** [comment]
@tanvimoharir I am happy to demur if you want the PR

**Comment by tanvimoharir** [comment]
@effigies @bryevdv Thank you.
I will work on this.

**Comment by tanvimoharir** [comment]
Hi, 
I have started working on this and have pushed few changes. While there are still more changes that I have to make,please feel free to refer #250 

Also I wanted to ask how do we take care of 'attribute-defined-outside-init'  (Refer below warnings)

versioneer.py:344:4: W0201: Attribute 'VCS' defined outside __init__ (attribute-defined-outside-init)
versioneer.py:345:4: W0201: Attribute 'style' defined outside __init__ (attribute-defined-outside-init)
versioneer.py:346:4: W0201: Attribute 'versionfile_source' defined outside __init__ (attribute-defined-outside-init)
versioneer.py:347:4: W0201: Attribute 'versionfile_build' defined outside __init__ (attribute-defined-outside-init)
versioneer.py:348:4: W0201: Attribute 'tag_prefix' defined outside __init__ (attribute-defined-outside-init)
versioneer.py:350:8: W0201: Attribute 'tag_prefix' defined outside __init__ (attribute-defined-outside-init)
versioneer.py:351:4: W0201: Attribute 'parentdir_prefix' defined outside __init__ (attribute-defined-outside-init)

Should this be suppressed?
Additionally I just wanted to mention that I'm fairly new in contributing to open source and any feedback or suggestions are more than welcome.
Thanks!

**Comment by tanvimoharir** [comment]
@effigies and @bryevdv  Is there anything more that you think can be done here? I would be happy to work further on this.
Thanks

**Comment by effigies** [comment]
Running pylint on the latest versioneer:

```
$ pylint versioneer.py
************* Module versioneer
versioneer.py:398:12: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)

------------------------------------------------------------------
Your code has been rated at 9.98/10 (previous run: 9.98/10, -0.00)
```

Seems fine?

**Comment by tanvimoharir** [comment]
@effigies I will take a look into this. It generally (from what I have seen) expects a score of 10 in most cases.

**Comment by tanvimoharir** [comment]
#257

**Comment by effigies** [comment]
Thanks! I think we can close this at this point.
