### ISSUE TITLE
no version when using pip install but correct when using setup.py install

### ISSUE THREAD

**Issue by renato-lombardo** [python-versioneer/python-versioneer#248]
I've a small package (e.g. `mypack`) with a standard directory structure where `.git `and `setup.py `are on the same level while `__init__.py` and `_version.py` are inside a dir with the name `mypack`:
```
Code/.git
Code/setup.py
Code/mypack/__init__.py
Code/mypack/_version.py
```
I created versioneer section inside `setup.cfg` like this:
```
[versioneer]
VCS = git
style = pep440
versionfile_source = mypack/_version.py
tag_prefix =''
```
And I use this `pyproject.toml`, including `versioneer-518` as suggested in [#193](https://github.com/python-versioneer/python-versioneer/issues/193) :
```
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "versioneer-518"
]
build-backend = "setuptools.build_meta"
```
When I build the package with `python -m build `(or with `python setup.py sdist bdist_wheel`) I obtain the two files:
```
mypack-0.1a0+1.g6317c20.tar.gz
mypack-0.1a0+1.g6317c20-py3-none-any.whl
```
The problem is that if I install  using `pip install mypack-0.1a0+1.g6317c20-py3-none-any.whl` I get this behaviour:
```
In [1]: import mypack
In [2]: mypack.__version__
Out[2]: '0+unknown'
```
However, if I install using `python setup.py install` I correctly get:
```
In [1]: import mypack
In [2]: mypack.__version__
Out[2]: '0.1a+1.g6317c20'
```
I am using pip 21.0.1 (python 3.6) on a Ubuntu 18.04 for installing. 
Does anyone have some suggestion on how to fix this?

**Comment by effigies** [comment]
What does your setup.py look like?

**Comment by renato-lombardo** [comment]
This is my setup.py
```
import versioneer
from setuptools import setup
setup(
    version=versioneer.get_version(),
    cmdclass=versioneer.get_cmdclass()
)
```

**Comment by effigies** [comment]
The most likely cause would be the absence of versionfile_build in your setup.cfg. It should generally be the same as versionfile_source.

**Comment by renato-lombardo** [comment]
Thank you! That was it! I thought that versionfile_build was needed only if I had src/mypack
