### ISSUE TITLE
FYI: versioningit might be a viable alternative

### ISSUE THREAD

**Issue by yarikoptic** [python-versioneer/python-versioneer#259]
Tireless @jwodder crafted the https://github.com/jwodder/versioningit which we are considering as a replacement for versioneer to provide a bit more contemporary setup and not requiring digging versioneer for workarounds in some ad-hoc scenarios (like for #255 etc).

A sample PR converting from versioneer to versioningit : https://github.com/dandi/dandischema/pull/56 .  If anyone interested to try -- feedback might become very valuable ;)

Close upon reading since not really an issue ;)

**Comment by effigies** [comment]
Thanks, Yarik. Added versioningit to the README.
