### ISSUE TITLE
pythonw.exe opens console window

### ISSUE THREAD

**Issue by CSchulzeTLK** [python-versioneer/python-versioneer#284]
If a module using versioneer is imported from in a pythonw.exe, then a console window is visible for each call to git.exe/git.cmd. The subprocess.Popen call should set the startupinfo argument.

This code will open a console window when executed by pythonw.exe:
```python
import subprocess
command = ['git', '--help']
subprocess.Popen(command).wait()
```

This code does not open a console window:
```python
import subprocess
command = ['git', '--help']
startupinfo = subprocess.STARTUPINFO()
startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
subprocess.Popen(command, startupinfo=startupinfo).wait()
```

subprocess.STARTUPINFO is only available on windows.

**Comment by effigies** [comment]
Would you be interested in submitting a PR to use this? I think inserting a kwarg is probably the cleanest way.

```Python
kwargs = {}
if windows:
    startupinfo = subprocess.STARTUPINFO()
    startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
    kwargs["startupinfo"] = startupinfo
subprocess.Popen(command, **kwargs).wait()
```
