### ISSUE TITLE
`build_ext` fails if `build_py` was not called before

### ISSUE THREAD

**Issue by mgorny** [python-versioneer/python-versioneer#296]
For example in [aesara](https://github.com/aesara-devs/aesara):

```
$ python setup.py build_ext -j12
running build_ext
UPDATING build/lib/aesara/_version.py
error: [Errno 2] No such file or directory: 'build/lib/aesara/_version.py'
```

**Comment by effigies** [comment]
During standard `python setup.py install`, I think `build_py` is called before `build_ext`, but it is not always the case that someone will want to call `build_py` implicitly in `build_ext`. For example, here is a [StackOverflow post](https://stackoverflow.com/questions/29477298/setup-py-run-build-ext-before-anything-else) asking how to avoid running `build_py` before `build_ext`.

I note that we do avoid running the update if you use `--inplace`. Would updating your above command to `python setup.py build_ext -j12 --inplace` get you what you want?

**Comment by mgorny** [comment]
Building in-place is not an option for us, as separate build dirs are required to handle different versions of Python.

**Comment by mgorny** [comment]
For the record, the problem is related to the Python build infrastructure for Gentoo packages. I suppose the alternative "fix" would be to skip updating the version if `build_py` wasn't called but I'm not really sure how to check that. I suppose checking if build dir could be an option.

**Comment by effigies** [comment]
Might make sense to warn if the file doesn't exist with an error message that explains that it couldn't be updated and you might need to `build_py` first.

Setup.py does also allow you to pass multiple commands, each with their own options. For this use case, maybe:

```
python setup.py build_py build_ext -j12
```

**Comment by mgorny** [comment]
The whole point is to avoid calling `build_py` because it makes everything much slower (and it's very slow anyway), and PEP517 build takes care of calling it anyway.

**Comment by mgorny** [comment]
…and updated!
