### ISSUE TITLE
Changing tag prefix from a string to null appears to make _version.py use string literal "None"

### ISSUE THREAD

**Issue by dasturge** [python-versioneer/python-versioneer#300]
Using versioneer 0.22

I was trying to fix an issue where I accidentally used tag_prefix in setup.cfg and ended up commenting it out and reinstalling versioneer to the repo:

before:
```
[versioneer]
VCS = git
style = pep440
versionfile_source = myrepo/_version.py
#versionfile_build =
tag_prefix = myrepo
#parentdir_prefix =
```

after:
```
[versioneer]
VCS = git
style = pep440
versionfile_source = myrepo/_version.py
#versionfile_build =
#tag_prefix =
parentdir_prefix = myrepo
```

On reinstall I found this in the _version.py:

```
def get_config():
    """Create, populate and return the VersioneerConfig() object."""
    # these strings are filled in when 'setup.py versioneer' creates
    # _version.py
    cfg = VersioneerConfig()
    cfg.VCS = "git"
    cfg.style = "pep440"
    cfg.tag_prefix = "None"
    cfg.parentdir_prefix = "myrepo"
    cfg.versionfile_source = "myrepo/_version.py"
    cfg.verbose = False
    return cfg
```

Haven't seen this before but it may have to do with changing it to null on an existing installation.

**Comment by effigies** [comment]
Yeah... I think instead of commenting it out, you should just change it to `tag_prefix = ` and it will be the empty string.

We should probably handle this case better.

**Comment by effigies** [comment]
Looks like the trivial fix I put in broke tests. What I deserve...

Reopening until I have time to look into whether these tests do something useful or just need to be updated.
