### ISSUE TITLE
Why the wheel is dirty even this git status is clean?

### ISSUE THREAD

**Issue by chaokunyang** [python-versioneer/python-versioneer#301]
![image](https://user-images.githubusercontent.com/12445254/165879043-a85ee95c-cb0b-4d78-be80-008a716f55bf.png)
My git checkout is clean, but the built wheel is `pymars-0.9.0+0.ga505786d.dirty-cp37-cp37m-linux_x86_64.whl`
![image](https://user-images.githubusercontent.com/12445254/165879145-cf51ba9b-58b6-4f5a-93ad-32d7d09ceb46.png)

Is there anything I miss? the code is already on a tag `v0.9.0`, no uncommitted changes in local.

**Comment by chaokunyang** [comment]
I've checked local changes using 
```
git status
git describe --tags --dirty --always
git diff --diff-filter=ACRM --exit-code
```

All shows no local changes.

**Comment by effigies** [comment]
How are you building your package?

**Comment by chaokunyang** [comment]
It's a mistake in my CI configuration, I built my wheel twice, the first time made some changes to my source tree.
