### ISSUE TITLE
Question about advanced semantic version numbers. :help-wanted: :more-info-needed: :version scheme:

### ISSUE THREAD

**Issue by bmmcwhirt** [python-versioneer/python-versioneer#302]
I am trying to figure out how to use versioneer to align my version numbers with by branching strategy. I use a Features[] > Dev > Main strategy. So my versions with semantic versioning should look like this:

vM.m.(P/H)-Jira Feature Branch+Build
M = Major(Release, Dev, Patch, Hot Fix) "\d"
m = Minor(Release)  (any even number)
m = Minor(Dev) (any odd number)
P = Patch(Dev) (any odd number or 0)
H = Hot Fix(Release)  (any even number)

Hot Fixes are only applied to to Release
Patches are only applied to Dev

Here are examples with the regex.

Release with Hotfix.
v35.14.216-SNOW_INC01827364+05078  :  v(\d*[0-9])(\.)(\d*[24680])(\.)(\d*[24680]\d[2468])(-)(\w*-*\w*)(\+)(\w{5})

Release with no hot fix.
v35.14.0-JIRA-367_Release+05078  :  v(\d*[0-9])(\.)(\d*[24680])(\.)([0])(-)(\w*-*\w*)(\+)(\w{5})

Dev with patch.
v35.15.125-JIRA-367_Dev+05078  :  v(\d*[0-9])(\.)(\d*[13579])(\.)(\d*[13579])(-)(\w*-*\w*)(\+)(\w{5})

Dev no patch
v35.15.0-JIRA-367_Feature876+05078  :  v(\d*[0-9])(\.)(\d*[13579])(\.)([0])(-)(\w*-\w*)(\+)(\w{5})

**Comment by effigies** [comment]
I don't think versioneer is this customizable without actually modifying the code. You might want to look at something like versioningit.
