### ISSUE TITLE
Version style mode compatabile with Azure Devops

### ISSUE THREAD

**Issue by Tclv** [python-versioneer/python-versioneer#304]
Hi, thanks for this very nice package.

I have question regarding version numbering style on azure devops. For some reason it doesn't seem to accept any style on upload besides pep440-old and pep440-pre, which have the downside of not having a short hash to disambiguate between branches and rebasing which might result in conflicts. See also https://developercommunity.visualstudio.com/t/cant-upload-package-with-tag-format-majorminorpatc/743758 and https://developercommunity.visualstudio.com/t/local-version-segments-for-python-package-feeds/892057. I was wondering if you have encountered this before and know of a workaround. Thanks in advance.

**Comment by effigies** [comment]
I don't think so. This seems to be a decision on the Azure side (PyPI also does not allow local versions for the time being), and there's not much we can do. If you have an alternative version mode you would like to propose, please do.
