### ISSUE TITLE
pass stderr in verbose mode from running git commands?

### ISSUE THREAD

**Issue by yarikoptic** [python-versioneer/python-versioneer#310]
e.g. 

```patch
diff --git a/versioneer.py b/versioneer.py
index a48dcce97..da5916f23 100644
--- a/versioneer.py
+++ b/versioneer.py
@@ -1196,7 +1196,7 @@ def git_pieces_from_vcs(tag_prefix, root, verbose, runner=run_command):
     runner = functools.partial(runner, env=env)
 
     _, rc = runner(GITS, ["rev-parse", "--git-dir"], cwd=root,
-                   hide_stderr=True)
+                   hide_stderr=not verbose)
     if rc != 0:
         if verbose:
             print("Directory %s not under git control" % root)
```

since including the fact that I needed `-v` for `pip install` to see this verbose, took awhile to troubleshoot the need to overcome recent git's check for safety:

```shell
$ sudo git "rev-parse" "--git-dir"
fatal: unsafe repository ('/home/travis/build/datalad/datalad' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /home/travis/build/datalad/datalad
The command "sudo git "rev-parse" "--git-dir"" exited with 128.
```
in case of installing via `sudo` from a local git repo (that is how we test datalad on travis).

More of pains could be shared from https://github.com/datalad/datalad/pull/6913

**Comment by effigies** [comment]
Seems fine. How do you enable verbose mode? Environment variable?

**Comment by effigies** [comment]
I guess we'd need to know how `pip -v` gets passed into `setuptools` subcommands and how those are exposed where we can get at them in versioneer.

**Comment by yarikoptic** [comment]
someone could indeed do that digging, or just observe that there is a `verbose` option for that function, and thus possibly makes sense to make running of the underlying commands "not hiding errors" if in verbose mode ;-)

**Comment by effigies** [comment]
Ah, right. Sure. Feel free to submit a patch. It seems we activate that with the `verbose` flag in `setup.cfg`.
