### ISSUE TITLE
Replace CC0 or add additional public domain-like license option

### ISSUE THREAD

**Issue by richardfontana** [python-versioneer/python-versioneer#315]
Fedora (which packages python-versioneer) recently [reclassified CC0 as disallowed for code](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/RRYM3CLYJYW64VSQIXY6IF3TCDZGS6LM/
) because it has a clause that precludes the granting of a patent license, which we consider to be inconsistent with FOSS legal norms. 

While we likely will grant some sort of exception for packages that were already in Fedora as of the date of the reclassification, I am wondering if you would consider either changing the license to another ultra-permissive option that does not have the "no patent licenses" clause problem (examples: MIT-0, 0BSD, Unlicense) or dual-license python-versioneer under CC0 and one of these other licenses.

**Comment by effigies** [comment]
The repository was published under the terms "public domain". #291 complained this was ambiguous, and we changed to CC0 in #292, which I understand to be the equivalent of releasing into the public domain.

Looking at [unlicense](https://spdx.org/licenses/Unlicense.html), this seems fine. @bastianzim, WDYT?

**Comment by BastianZim** [comment]
Unlicense is also fine with me so I'm happy either way. :) And yes, seems like that is the way to go if that helps Fedora as both licenses seem pretty much the same.

**Comment by richardfontana** [comment]
Thank you!
