### ISSUE TITLE
*cmd_sdist.make_release_tree* doesn't define *versions*.

### ISSUE THREAD

**Issue by dsoprea** [python-versioneer/python-versioneer#32]
_versions_ is referenced but not defined. This hasn't previously shown up because I haven't been changing or testing _sdist_ and/or _sdist upload_. This will be fixed by a commit in a moment.

**Comment by effigies** [comment]
This appears to have been fixed:

https://github.com/python-versioneer/python-versioneer/blob/6b555078bec6286dbbb46f8ae9c775597e162186/src/cmdclass.py#L172-L182
