### ISSUE TITLE
Update versioneer-518

### ISSUE THREAD

**Issue by gentlegiantJGC** [python-versioneer/python-versioneer#320]
Versioneer-518 has not been updated in a while.

I am trying to use versioneer with a src layout but I get an error that `src/package/_version.py` does not exist.
The latest version of versioneer does not have this issue so I assume that it has been fixed but the 518 version just has not gotten an update.

**Comment by effigies** [comment]
To install/upgrade versioneer, you still use the regular versioneer tool. However, by adding versioneer-518 to your pyproject.toml, you should be able to avoid adding the `versioneer.py` file.

That said, would you be interested in test driving #294?

```
pip install git+https://github.com/effigies/python-versioneer@enh/pep518-mode
versioneer install --no-vendor
```

Then you'll need to add `"versioneer @ git+https://github.com/effigies/python-versioneer@enh/pep518-mode"` to your `pyproject.toml`.

Once this is merged, we can drop versioneer-518 entirely.

**Comment by gentlegiantJGC** [comment]
Yes that does seem to work correctly.

I can't reproduce the original issue in minimal example. Not sure what was going wrong earlier. The _version.py file did exist in the source.

I will close this since it seems like you have this sorted.
