### ISSUE TITLE
Versioneer keeps returning 0+untagged

### ISSUE THREAD

**Issue by orkenstein** [python-versioneer/python-versioneer#325]
Just installed a fresh copy of non-vendored versioneer 0.24 in my git repo.
The `python3 setup.py version` gives:
```
running version
keywords are unexpanded, not using
got version from VCS {'version': '0+untagged.36.gef18964', 'full-revisionid': 'ef1896454cff6769d92420c72737065076fc71a0', 'dirty': False, 'error': None, 'date': '2022-08-31T18:59:48+0200'}
Version: 0+untagged.36.gef18964
 full-revisionid: ef1896454cff6769d92420c72737065076fc71a0
 dirty: False
 date: 2022-08-31T18:59:48+0200
 ```

However `git tag` returns multiple tags in `develop` branch. What might be wrong?

**Comment by effigies** [comment]
Can you run `git describe --tags`?

**Comment by orkenstein** [comment]
> Can you run `git describe --tags`?

```
v2.0.1-develop.1-1-gef18964
```

**Comment by effigies** [comment]
I see. What is your `tag_prefix` in `setup.cfg`?

**Comment by orkenstein** [comment]
> I see. What is your `tag_prefix` in `setup.cfg`?

The whole `setup.cfg` looks like:
```
[versioneer]
VCS = git
style = pep440
versionfile_source = tokenizer/_version.py
versionfile_build = tokenizer/_version.py
tag_prefix =
parentdir_prefix = filmustage-tokenizer-
```
My file structure is:
<img width="326" alt="CleanShot 2022-08-31 at 19 52 58@2x" src="https://user-images.githubusercontent.com/1461936/187746334-cad6d6f0-0a73-476e-b386-2579c29698ee.png">

**Comment by effigies** [comment]
You're going to need your `tag_prefix = v`. Once, you do that, you should get something like:

```
$ python setup.py version         
/miniconda3/lib/python3.8/site-packages/setuptools/dist.py:544: UserWarning: The version specified ('2.0.1-develop.1+1.gd91a1f1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running version
keywords are unexpanded, not using
got version from VCS {'version': '2.0.1-develop.1+1.gd91a1f1', 'full-revisionid': 'd91a1f1826a398e5989ed008a06e7c003a20fb42', 'dirty': False, 'error': None, 'date': '2022-08-31T14:08:43-0400'}
Version: 2.0.1-develop.1+1.gd91a1f1
 full-revisionid: d91a1f1826a398e5989ed008a06e7c003a20fb42
 dirty: False
 date: 2022-08-31T14:08:43-0400
```

This isn't PEP-440 compliant, but there is no way in versioneer to strip off the `-develop.1` suffix. Other tools like versioningit or setuptools_scm might have that kind of feature.

**Comment by orkenstein** [comment]
Thank you, it helped. Warning is OK, I think, since in `master` it gonna be clean.

**Comment by orkenstein** [comment]
@effigies now I see what do you mean by `isn't PEP-440 compliant`. When I try to install from develop, I get:
```bash
  Building wheel for filmustage-tokenizer (pyproject.toml) ... done
  WARNING: Built wheel for filmustage-tokenizer is invalid: Metadata 1.2 mandates PEP 440 version, but '2.0.1-develop.4' is not
ERROR: Could not build wheels for filmustage-tokenizer, which is required to install pyproject.toml-based projects
```
Should I set `style = pep517` or what's the recommended way to handle this on your opinion?
Thanks in advance

**Comment by effigies** [comment]
Versioneer is really only set up to work with PEP-440 tags, so your dev-branch marking tag could become something like `2.0.1.dev1`. From there, versioneer would create tags like `2.0.1.dev1+1.gd91a1f1`.

If you want to keep your current tag style, you're going to need a different tool (or contribute a patch here...). versioningit does have a lot of flexibility here. See https://versioningit.readthedocs.io/en/stable/configuration.html#the-tool-versioningit-tag2version-subtable

**Comment by orkenstein** [comment]
Changing pre-release appendix to `dev` worked like a charm. Thanks!
