### ISSUE TITLE
Contents of "src/from_file.py" not correctly escaped.

### ISSUE THREAD

**Issue by dsoprea** [python-versioneer/python-versioneer#33]
I'm getting this error:

```
ValueError: unsupported format character 'v' (0x76) at index 697
```

Because the contents of _from_file.py_ includes the following:

```
return version_string_template % versions
```

This will be fixed by a commit in a moment.

**Comment by warner** [comment]
You aren't still seeing this, are you? I think it should have been fixed a long time ago.

**Comment by effigies** [comment]
Please reopen if still relevant.
