### ISSUE TITLE
versions_from_file() doesn't appear to work

### ISSUE THREAD

**Issue by dsoprea** [python-versioneer/python-versioneer#34]
After I do an "sdist upload" of a package, a "pip3 install <package>" fails because the version can't be recovered from _version.py, and there isn't going to be any VCS metadata to fallback on.

This is essentially the main content of my _version.py (in the package about to be downloaded and installed via _pip_):

``` python
versions = {'full_revisionid': '7574780f82745fcfeec579d11628cbae9721fdb8', 'describe': '0.3.10', 'dash_dirty': '', 'distance': 0, 'default': '0.3.10', 'closest_tag_or_zero': '0.3.10', 'pep440': '0.3.10', 'long': '0.3.10-0-g7574780', 'closest_tag': '0.3.10', 'dirty': False, 'short_revisionid': '7574780', 'dash_distance': ''}

def get_versions(default={}, verbose=False):
    return versions

def get_version():
    return version_string_template % versions
```

However, none of the following conditionals hit (none of the lines match):

```
            for line in f.readlines():
                mo = re.match("version_version = '([^']+)'", line)
                if mo:
                    versions["version"] = mo.group(1)
                mo = re.match("version_full = '([^']+)'", line)
                if mo:
                    versions["full"] = mo.group(1)
```

This bug means that PyPI-based installs will always fail. Please confirm. I think this predates my changes.

**Comment by warner** [comment]
I think this should be fixed by now. Could you retest?

**Comment by effigies** [comment]
Many packages now upload sdists built with versioneer, so this should be resolved.
