### ISSUE TITLE
`setup.py` from git fails if `versioneer<=0.23` is installed

### ISSUE THREAD

**Issue by mgorny** [python-versioneer/python-versioneer#343]
Noticed this because Gentoo users hit upgrade problem. If `versioneer==0.23` is installed on the system, `setup.py` run from a git clone/snapshot fails because it tries to use it:

```pytb
$ python setup.py build
Traceback (most recent call last):
  File "/tmp/python-versioneer/setup.py", line 143, in <module>
    VERSION = versioneer.get_version()
              ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'versioneer' has no attribute 'get_version'
```

Having to uninstall the previous version prior to building the new one would be fairly inconvenient, and I can't think of a proper `PYTHONPATH` hack that would prevent the old version from being imported.

**Comment by mgorny** [comment]
For the record, I've just thought of a good workaround: I've put a fake `versioneer.py` that just raises an `ImportError` in a temporary directory and put that in `PYTHONPATH`.

**Comment by effigies** [comment]
Right, this does assume people are using build isolation to build their packages. I don't really know what Gentoo is doing, but shouldn't it be possible to use `python -m build` to get a wheel and unzip it, or allow `pip ` to do that with `pip install --prefix ...`?

Calling `python setup.py` directly is no longer supported by setuptools at all, so it seemed reasonably safe to count on build isolation.

**Comment by effigies** [comment]
You could patch `setup.py`:

```Diff
 try:
     import versioneer
+    if not hasattr(versioneer, "get_version"):
+        raise ImportError("Too old of versioneer; bootstrap")
 except ImportError:
     # Bootstrap a versioneer module until it's built
     from importlib import util as ilu
     versioneer = ilu.module_from_spec(ilu.spec_from_loader('versioneer', loader=None))
     exec(generate_versioneer_py(), versioneer.__dict__)
```

I guess the long-term better solution would just be to always bootstrap. Any interest in submitting the PR?

**Comment by effigies** [comment]
Well, the point of the process is that I have limited time. I'm happy to talk things through when I'm scrolling through GitHub notifications, but actually making the changes, testing, committing and writing up a PR take some time and effort (in this case pretty small). I would appreciate it if you did take the time, though. That will also ensure that it gets done sooner, and not when I happen to have some free minutes and remember this thread, and you'll be credited in the git history and release notes.

To your question, though, yes. I would also update the comment and move the import to the top.

**Comment by mgorny** [comment]
Ok, thanks for the explanation. I'll do it in a minute.
