### ISSUE TITLE
Git replacements may not always be applied

### ISSUE THREAD

**Issue by dsoprea** [python-versioneer/python-versioneer#35]
It looks like .gitattributes has the right stuff, but the replacements aren't happening into _version.py after the commit/tag (for me).

Any idea what could be happening?

I sent you an email, but you must've missed it.

**Comment by warner** [comment]
Are you still seeing this? (the replacements will only happen in a `git archive` tarball, in case you were expecting otherwise.. regular git checkouts don't get the replacements).

**Comment by effigies** [comment]
Please reopen if this is still relevant.
