### ISSUE TITLE
not under git control unable to compute version

### ISSUE THREAD

**Issue by Honst211** [python-versioneer/python-versioneer#351]
Windows runs "python setup.py version" display not under git control unable to compute version.
I need to distribute through github on Windows. How can I do this

**Comment by effigies** [comment]
Hi, sorry, you're going to need to provide more details of what you've tried to do. This isn't going to be enough. I would suggest Googling "How to ask a good question" or similar to see what people need. Here's [one from StackOverflow](https://stackoverflow.com/help/how-to-ask).

**Comment by Honst211** [comment]
Sorry, there was a problem in my use, and now the problem has been solved
