### ISSUE TITLE
Issue with Mac's Homebrew python, and issue when not using __legacy__ build meta

### ISSUE THREAD

**Issue by kiyoon** [python-versioneer/python-versioneer#357]
I found two problems.

The first one occurs with Mac. It seems like my package released with versioneer doesn't work well with mac. I used the new non-vendored mode with `pyproject.toml`.  
https://github.com/kiyoon/jupynium.nvim/issues/2

So I tried to make it non-vendored. However, it also doesn't work with `pip install .` even on Linux. `python setup.py install` works.  
I found that the solution is to go to the __legacy__ mode.

Is there any solution to this?

**Comment by effigies** [comment]
Your second issue is covered by https://github.com/python-versioneer/python-versioneer/issues/249.

I have no idea why Homebrew Python would work differently from other Pythons. I'll leave this open in case anybody else can contribute.

**Comment by kiyoon** [comment]
> Your second issue is covered by #249.
> 
> I have no idea why Homebrew Python would work differently from other Pythons. I'll leave this open in case anybody else can contribute.

I have a feeling it's a bug from Homebrew python, if it can't install extra dependencies. It is frustrating that I need to go to legacy just because of this.. Thanks for your comment and hopefully someone can find the solution!

**Comment by kiyoon** [comment]
I did some digging and found out.
The problem was that it wasn't able to build from build-time dependency because of homebrew's custom `sitecustomize` module not finding a proper path.  
See https://sitetools.readthedocs.io/en/latest/path.html

You can find the error message if you run `pip` like `SETUPTOOLS_SCM_DEBUG=1 PYTHONVERBOSE=1 python3 -m pip install -vvv .`  
```python
assert not path in sys.path
```

This has been already fixed, although not included in the official pip yet.  
https://github.com/pypa/pip/issues/11539
