### ISSUE TITLE
Versioneer does not detect git tag version

### ISSUE THREAD

**Issue by wxguy** [python-versioneer/python-versioneer#362]
Installed the `versioneer` package from conda. Here is the version I am using:

```
versioneer --version
versioneer (installer) 0.28
```
Here is my git tag details of source code:

```
git describe --tags
v0.3.1
```

After running `versioneer install` and `python versioneer.py setup`, I get the following output:

``
python wrfplot/wrfplot.py --version
0+untagged.64.g697c084.dirty
``

Here is my setup.cfg configuration:

```
[versioneer]
VCS = git
style = pep440
versionfile_source = wrfplot/_version.py
versionfile_build = wrfplot/_version.py
tag_prefix = v
parentdir_prefix = wrfplot-
```

and here is my `__init__.py` file content:

```
from . import _version
__version__ = _version.get_versions()['version']
```

This creates an issue for me as PyPi does not accept the tag generated by versionee. 

Am I doing something wrong?

**Comment by Callek** [comment]
@wxguy - Is this still an issue for you, did you ever solve it, etc?

Looking to see if I can either clarify things in our docs, fix a bug, or try and clarify things for you [in addition to our docs] if it's useful.

**Comment by wxguy** [comment]
Thanks for the heads-up. The issue was sorted out but forgot to close.
