### ISSUE TITLE
"versioneer install" doesn't work as anticipated

### ISSUE THREAD

**Issue by MarkWieczorek** [python-versioneer/python-versioneer#369]
I installed versioneer (0.28) using conda, but `versioneer install` doesn't work as anticipated.

`versioneer install --no-vendor` gives the following output, complaining that "Versioneer was unable to run the project root directory"

```
Traceback (most recent call last):
  File "/Users/lunokhod/miniconda3/envs/test311/bin/versioneer", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/lunokhod/miniconda3/envs/test311/lib/python3.11/site-packages/versioneer.py", line 1931, in main
    setup_command()
  File "<string>", line 2197, in setup_command
  File "<string>", line 2104, in do_setup
  File "<string>", line 356, in get_root
versioneer.VersioneerBadRootError: Versioneer was unable to run the project root directory. Versioneer requires setup.py to be executed from its immediate directory (like 'python setup.py COMMAND'), or in a way that lets it use sys.argv[0] to find the root (like 'python path/to/setup.py COMMAND').
```

If I intsead just use "`versioneer install` it created the two files
```
versioneer.py (0.28) installed into local tree
Now running 'versioneer.py setup' to install the generated files..
 creating ctplanet/_version.py
 appending to ctplanet/__init__.py
Traceback (most recent call last):
  File "/Users/lunokhod/miniconda3/envs/test311/bin/versioneer", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/lunokhod/miniconda3/envs/test311/lib/python3.11/site-packages/versioneer.py", line 1931, in main
    setup_command()
  File "<string>", line 2198, in setup_command
  File "<string>", line 2163, in scan_setup_py
FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
```
but then crashes complaining that there is no `setup.py` file. I don't have a setup.py, and in my `pyproject.toml` file, I have the following relevant lines

```
[build-system]
requires = ["setuptools", "wheel", "versioneer[toml]==0.28"]
build-backend = "setuptools.build_meta"

[tool.versioneer]
VCS = 'git'
style = 'pep440'
versionfile_source = 'ctplanet/_version.py'
versionfile_build = 'ctplanet/_version.py'
tag_prefix = ''
parentdir_prefix = 'ctplanet-'
```

When installing the project, it ends with 

```
Successfully installed ctplanet-0.0.0
```
but the version number is incorrect: 
```
git describe --tags
v0.2.3
```
Just to be certain, I created a new environment and started over, but got the same effect. If it matters, I am running this on macos (apple silicon).

**Comment by Callek** [comment]
Hi @MarkWieczorek.

Currently `versioneer` must be used with a setup.py and is not supported without one. https://github.com/python-versioneer/python-versioneer#quick-install

In both ways of installing it, once you have it setup and installed you can verify the version information with:
`python setup.py version`  as per those docs.

Specifically there are a few entries to setup.py that as of my last checking were not configurable in setup.cfg alone, so see Step 5 of https://github.com/python-versioneer/python-versioneer/blob/master/INSTALL.md#common-steps for the pieces you need to add for `versioneer` in a setup.py.

**Comment by benjaesq** [comment]
The README mentions that pyproject.toml is experimental
