### ISSUE TITLE
Release new version of versioneer

### ISSUE THREAD

**Issue by Callek** [python-versioneer/python-versioneer#372]
@effigies - Seems with the pdm patch I just merged, we probably should release a new version.

Do you want to handle that at this time, or do you want to grant me pypi access to do it myself?  - Is there any process you've used in the past that you want me to be sure I continue?

**Comment by effigies** [comment]
Versioneer now versions itself, so you should be able to just push a tag (preferably annotated) to GitHub and it'll go. There is a PYPI token in the secrets.

I do have push permissions, but not admin permissions, on PyPI. I'm not sure who can add you. Almost certainly @warner, but perhaps @yarikoptic or @bucknerns.

**Comment by effigies** [comment]
Other part of release process is update https://github.com/python-versioneer/python-versioneer/blob/master/NEWS.md, and any special instructions to https://github.com/python-versioneer/python-versioneer/blob/master/UPGRADING.md. And make sure that the metadata in the README/pyproject.toml is correct. For example, I think we need to advertise 3.11 support.

**Comment by Callek** [comment]
I'll tackle this tonight, with an update for NEWS/etc with a planned release for tomorrow (July 7).  And push the tag tomorrow after I have given you a chance to review the NEWS update and such.

(I had missed that our tox github workflow also did the publish step)

**Comment by Callek** [comment]
Released https://github.com/python-versioneer/python-versioneer/releases/tag/0.29

**Comment by effigies** [comment]
Thanks!
