### ISSUE TITLE
Doesn't work with Python 3.12

### ISSUE THREAD

**Issue by mbridon** [python-versioneer/python-versioneer#375]
I'm trying to build [BuildStream](https://github.com/apache/buildstream/) on Fedora 39 which has Python 3.12, and [it fails](https://github.com/apache/buildstream/issues/1855) :disappointed: 

Once again, fedora is first on the latest and greatest, and we're the one finding issues in a lot of software. :shrug:

I think that issue in BuildStream should give you all you need to fix the issue in versioneer:

```
commit 06ca13b4181c9140a536a72086a324e242ec249b (HEAD -> main)
Author: Mathieu Bridon <mathieu@hashbang.coop>
Date:   Tue Aug 8 09:28:01 2023 +0200

    Try to fix #1855

diff --git a/versioneer.py b/versioneer.py
index 1c97e02..5751584 100644
--- a/versioneer.py
+++ b/versioneer.py
@@ -340,9 +340,16 @@ def get_config_from_root(root):
     # configparser.NoOptionError (if it lacks "VCS="). See the docstring at
     # the top of versioneer.py for instructions on writing your setup.cfg .
     setup_cfg = os.path.join(root, "setup.cfg")
-    parser = configparser.SafeConfigParser()
-    with open(setup_cfg, "r") as f:
-        parser.readfp(f)
+    if sys.version_info.major == 3 and sys.version_info.minor >= 12:
+        parser = configparser.ConfigParser()
+        with open(setup_cfg, "r") as f:
+            parser.read_file(f)
+
+    else:
+        parser = configparser.SafeConfigParser()
+        with open(setup_cfg, "r") as f:
+            parser.readfp(f)
+
     VCS = parser.get("versioneer", "VCS")  # mandatory
 
     def get(parser, name):
```

Can this be merged soon ? :zany_face:

**Comment by Callek** [comment]
I'll look at this no later than this upcoming weekend, thanks.

**Comment by nanonyme** [comment]
Commenting here too that with Python 3.2 SafeConfigParser was renamed to ConfigParser and SafeConfigParser was left as deprecated alias. So there most likely is no need for version checking given versioneer doesn't support Python 2.

**Comment by Callek** [comment]
@mbridon @nanonyme - So looking into this, there may still be some issues with py3.12 which I'm looking into to address now.... in #376 . though the *specific* issue mentioned in this ticket looks to have been fixed a while ago

https://github.com/python-versioneer/python-versioneer/commit/c8cf28fe58205cfcc40fc9abaf0e1c792d6e7b5a

Your vendored versioneer in Buildstream is 0.18 https://github.com/apache/buildstream/blob/cf694f158c90d9c085ef4459b5f6668ec6defc4d/versioneer.py#L3 which *did* support python2...

Vendoring is still a supported install method, though it does require you to update the actual vendored file when you need changes like this.

**Comment by mbridon** [comment]
Alright, thank you ❤️ 

About the vendredi version of versioneer, should we instead use a pip requirement? What do you recommend? 🤔

**Comment by Callek** [comment]
> About the vendredi version of versioneer, should we instead use a pip requirement? What do you recommend? 🤔

@mbridon - So, I'll say that right now the vendored version is fully supported, I am (in some slower-than-I'd-like) free time working on a formal support plan for what Versioneer does support.

I very recently took over maintenance here, and as you might imagine with Python deprecating a lot of how `setuptools` works this gets a bit complicated.

I suspect the forward-thinking way might be the [Build-Time dependency mode](https://github.com/python-versioneer/python-versioneer/blob/master/README.md#build-time-dependency-mode).  Though see https://github.com/python-versioneer/python-versioneer/blob/master/UPGRADING.md#upgrading-to-024 if that's the avenue you want to take.

I will plan to be sure to update our release notes and UPGRADING section if that ever changes.

**Comment by mortbauer** [comment]
Hm, just fell over this, python 3.12 is released so versioneer fails now :(, if this could be released it would be great.

**Comment by Callek** [comment]
> Hm, just fell over this, python 3.12 is released so versioneer fails now :(, if this could be released it would be great.

I don't know of any actual issue with python3.12 with the current released versioneer.

Its more likely your source code has a vendored copy that is older than our current release. (see https://github.com/python-versioneer/python-versioneer?tab=readme-ov-file#vendored-mode)

If there is indeed an issue in our current release can you please open a new issue with relevant details to reproduce?

**Comment by mortbauer** [comment]
A I see, that seems to be the case here, thanks for the very quick help
