### ISSUE TITLE
Simplify unicode handling in setup.py

### ISSUE THREAD

**Issue by roskakori** [python-versioneer/python-versioneer#62]
I noticed that `setup.py` has a few part of the code where is has to mess with the difference of dealing with unicode in Python 2 and 3. Here are some pointers that might help you in simplifying that, assuming Python 2.6 is the oldest version you want to support:

The `io` module offers an `open()` function that under Python 3 is just an alias for `open()` while under Python 2 provides an `open()` that does exactly the same as `open` under Python 3. So the following code works with Python 2 and 3 and builds a list of unicode strings:

``` python
import io
with io.open('some.txt', 'r', encoding='utf-8') as text_file:
    text_lines = list(text_file)
```

Also there is `io.StringIO` which under Python 2 provides a `StringIO` that internally uses unicode (unlike `StringIO.StringIO`). So `io.StringIO.write()` accepts unicode strings and `io.StringIO.getvalue()` returns a unicode string - just like under Python 3.

Finally, there is

``` python
from ___future__ import unicode_literal
```

which does nothing under Python 3 but changes the way string literal in the source code are interpreted under Python 2. For example,

``` python
some_text = 'this is some text'
```

would be the same as

```
some_text = u'this is some text'
```

If you really need a byte string, just use the 'b' prefix, which is available for Python 2.6 and Python 3, for example:

``` python
some_bytes = b'abcd'
```

**Comment by warner** [comment]
cool, thanks for the pointers!
