### ISSUE TITLE
version in develop mode is not pep440 compatible

### ISSUE THREAD

**Issue by marscher** [python-versioneer/python-versioneer#92]
In sdist versions it is fine, but if one has the project installed in develop mode (python setup.py develop) it still outputs the old format.

python setup.py version is fine:

```
got version from VCS {'error': None, 'version': '1.2.1+104.ge5a81e7.dirty', 'dirty': True, 'full-revisionid': 'e5a81e7c4c7aac56eb4e50dfa2757d1140ce1553'}
Version: 1.2.1+104.ge5a81e7.dirty
 full-revisionid: e5a81e7c4c7aac56eb4e50dfa2757d1140ce1553
 dirty: True
```

import the versioneered package in ipython:

```
In [1]: import pyemma
In [2]: pyemma.__version__
Out[2]: '1.2.1-104-ge5a81e7-dirty'
```

**Comment by reedstrm** [comment]
I do not see this with bare python. Is it an ipython artifact?

**Comment by marscher** [comment]
Could be the case.

**Comment by marscher** [comment]
But why should the content of the generated version be different then?

**Comment by reedstrm** [comment]
Hard to say. Is there a virtualenv involved? And what version of versioneer?

**Comment by marscher** [comment]
Its 0.15. I'm running this in a miniconda environment, so there is no
virtualenv involved.

**Comment by effigies** [comment]
From a quick `pip install -e pyemma`, I'm unable to reproduce this issue. Should this be closed, or is there a reproduction?

**Comment by marscher** [comment]
Thanks -this is fairly out dated and has been fixed in the meantime.
