### ISSUE TITLE
embbedded vs library

### ISSUE THREAD

**Issue by reedstrm** [python-versioneer/python-versioneer#96]
I find Versioneer an interesting tool to solve a thorny dev problem. I'm looking to adopt it for a number of projects, but am getting pushback from other developers about including the code directly in our trees. One dev mentioned it feels like the old ez_setup.py days. What are the design reasons behind copying versioneer.py (and the source tree version of _version.py) directly into the code repo, rather than providing them as development-required libraries? Now that I think about it, I'm not sure if there exists a mechanism to declare a development (as opposed to install or test) requirement. Hmm.

**Comment by ariscn** [comment]
+1. Just discovered versioneer a couple of days ago, so I'm still wrapping my head around how it works. Is there any way to avoid the redundancy of versioneer.py generating _version.py? It would be preferable if `app/__init__.py` could do `import versioneer` instead of `import ._version`.

**Comment by skolsuper** [comment]
+1. This is an unusual package.

**Comment by effigies** [comment]
Consolidating into #193.
