### ISSUE TITLE
README.md unclear about how to handle versionfile_build = None

### ISSUE THREAD

**Issue by KerstinKeller** [python-versioneer/python-versioneer#97]
README.md seems unclear as on how to handle `versionfile_build = None`. It states one has to "override `distutils.command.build_scripts` to explicitly insert a copy of `versioneer.get_version()` into your generated script."
It is very unclear to me, how and where I can achieve this. Do I need to modify setup.cfg? Any hints are appreciated.

**Comment by warner** [comment]
I added some text to README.md that points to an example.. is that helpful?

**Comment by effigies** [comment]
Please open a new issue if things are still unclear.
