### ISSUE TITLE
failure with git 1.7.1

### ISSUE THREAD

**Issue by little-dude** [python-versioneer/python-versioneer#98]
I have packages using versioneer that works fine with git 2.5.0 but that I cannot install using easy_install (`python setup.py install` or `python setup.py develop`).

```
$ python setup.py develop
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
 limiting output:
   --max-count=nr
   --max-age=epoch
   --min-age=epoch
   --sparse
   --no-merges
   --remove-empty
   --all
   --branches
   --tags
   --remotes
   --stdin
   --quiet
 ordering output:
   --topo-order
   --date-order
   --reverse
 formatting output:
   --parents
   --children
   --objects | --objects-edge
   --unpacked
   --header | --pretty
   --abbrev=nr | --no-abbrev
   --abbrev-commit
   --left-right
 special purpose:
   --bisect
   --bisect-vars
   --bisect-all
Traceback (most recent call last):
 File "setup.py", line 6, in <module>
   version=versioneer.get_version(),
 File "/mypackage/versioneer.py", line 1405, in get_version
   return get_versions()["version"]
 File "/mypackage/versioneer.py", line 1380, in get_versions
   pieces = from_vcs_f(cfg.tag_prefix, root, verbose)
 File "/mypackage/versioneer.py", line 1076, in git_pieces_from_vcs
   pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string or a number, not 'NoneType'
```

Is 1.7.1 supported? If not, how can I workaround this issue on systems using this old version?

**Comment by little-dude** [comment]
For the moment my "workaround" is to edit `setup.py` like this:

```from setuptools import setup
import versioneer

setup(name='mypackage',
      # version=versioneer.get_version(),
      # cmdclass=versioneer.get_cmdclass(),
      version='10.0.0'
      # more stuff [...]
)
```

**Comment by little-dude** [comment]
It appears that the issue has nothing to do with the git version.
The problem occurs because the tags are missing in the local repo.

**Comment by warner** [comment]
Oops. Repos without tags are supposed to give you a version of "0" plus the number of commits and a git hash. That error looks like we're giving git some arguments that it doesn't like. I thought we were testing the no-tags case, which makes me think that the older git version is reacting differently.

Could you see if the no-tags case behaves differently with different git versions? I'll look at that function and see what exactly it does when there are no tags.. maybe I can track down what it's telling git to do.

**Comment by warner** [comment]
It looks like `rev-list` is always called the same way (`git rev-list HEAD --count`), with no arguments that depend upon the state of the tree. I built a copy of git-1.7.1 and it understood the `--count` without problems, although I *did* have to comment out a `[push] default = simple` from my `~/.gitconfig` which was confusing it.

Is it possible that you usually use a new version of git, but somewhere on your $PATH is an older version, and somehow versioneer was using that instead?

I suppose we could change Versioneer to run git without its global config, but I suspect that'd end up being a really bad idea.

That rev-list command will only be run if you don't have any tags, so if there's a bug how we're calling some version of git, it will only show up in the no-tags case.

Could you make a Versioneer-controlled repo with no tags, and do `setup.py version` in it, and see if that error shows up again? If so, please run `git rev-list HEAD --count` in that tree and see what it does.
